th main.lua \
-depth 18 \
-batchSize 32 \
-nGPU 1 \
-nThreads 5 \
-data /media/eightbit/data_ssd/GenderData \
-dataset gender \
-nClasses 3 \
-resetClassifier false \
-backend cudnn \
-nEpochs 600 \
-classWeighting false \
-finetuneLastLayer true \
-retrain /media/eightbit/data_hdd/Libs/TorchLibs/fb.resnet.torch/my_models/gender/model_77.t7 \
-LR 0.000001 \
-LR_decay_step 200 \
-gen my_models/  \
-save my_models/gender/ \
-checkpoint true \
-gen cache_files \

#-retrain /media/eightbit/data_hdd/NNBase/Models/Torch/ImageNetResNet/resnet-18.t7 \
