th main.lua \
-batchSize 32 \
-nGPU 1 \
-nThreads 10 \
-data data/mnist/ \
-dataset triplet \
-resetClassifier true \
-nFeatures 256 \
-backend cudnn \
-nEpochs 100 \
-LR 0.01 \
-LR_decay_step 35 \
-optimizer sgd \
-gen cache_files/ \
-optnet true \
-save my_models/beauty/ \
-netType mnistnet \
# -model_init_LR 0.0001
